blog/urls.py
from django.urls import path
from .import views

app_name = 'blog' # 블로그 앱의 url에 name space 설정하도록 변경

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView #임포트

app_name = 'bookmark' # 북마크 앱의 url에 name space 설정하도록 변경

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'), # urlpatterns 변수에 path를 하나 더 추가해 BoookmarkCreateView를 연결
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'), # path를 추가하고 BookmarkDetailView를 연결
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Bookmark(models.Model): # models.Model을 상속받는 Bookmark 클래스 생성
    # 모델 안에 필드라 부르는 두 개의 클래스 변수 존재,
        # site_name, url 데이터베이스에 이 두가지의 정보를 저장하고자 함, 이 정보가 기록되는 테이블 이름은 bookmark임.
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    def __str__(self):
        # 객체를 출력할 때 나타날 값
        return "이름 : " + self.site_name + ", 주소 : " + self.url

    # get_absolute_url 메서드는 장고에서 사용하는 메서드, 보통 객체의 상세 화면 주소를 반환
        # 웹 사이트의 개별적인 모델 레코드들을 보여주기 위한 URL을 반환하는 메서드. 이 메소드가 추가되면, 관리자 사이트 안의 모델 레코드 수정화면에 View on site 버튼이 자동으로 추가됨
        # reverse() 함수는 모델의 개별적인 레코드들에 알맞은 포맷의 URL을 생성하는 역할
    def get_absolute_url(self):
        return reverse('bookmark:detail', args=[str(self.id)]) # reverse 메서드는 URL 패턴의 이름과 추가 인자를 전달받아 URL을 생성하는 메서드임

bookmark/views.py
from django.views.generic.list import ListView
from .models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView # UpdateView 임포트, DeleteView
from django.urls import reverse_lazy

from django.views.generic.detail import DetailView

# Create your views here.
# ListView를 상속받은 BookmarkListView 클래스형 뷰 생성
class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 6 # 한 페이지에 몇 개의 리스트 출력할 지 결정

class BookmarkCreateView(CreateView): # 제네릭 뷰인 CreateView를 상속받아 생성
    model = Bookmark # model : 어떤 모델의 입력을 받을 지 설정
    fields = ['site_name', 'url'] # fields : 어떤 필드들을 입력받을 지 설정하는 부분
    success_url = reverse_lazy('bookmark:list') # success_url : 북마크 추가를 완료하고 목록페이지로 이동
    template_name_suffix = '_create' # templates_name_suffix : 사용할 템플릿의 접미사만 변경하는 설정 값
    
class BookmarkDetailView(DetailView): # 제네릭 뷰인 DetailView를 상속받음
    model = Bookmark

class BookmarkUpdateView(UpdateView): # UpdateView를 상속받아 BookmarkUpdateview 생성
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update' # 템플릿 접미사를 _update로 설정하여, bookmark_update.html과 연결

class BookmarkDeleteView(DeleteView): # DeleteView를 상속받아, BookmarkDeleteView 생성
    model = Bookmark
    success_url = reverse_lazy('bookmark:list') # 목록 페이지로 가도록 reverse_lazy를 사용해 설정

bookmark/templates/bookmark/bookmark_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% extends 'base.html' %} <!--하위 템플릿은 항상 맨 윗줄에 [extends] 태그를 사용해 어떤 템플릿을 기준 템플릿으로 사용할지 결정-->

    {% block title %}Confirm Delete{% endblock %}

    {% block content %}
        <form action="" method="post"> <!--정보를 서버로 전달하기 위해 form 태그 사용-->
            {% csrf_token %} <!--form 태그 안에는 csrf_token을 꼭 함께 사용-->
            <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div><!--삭제할 것인지 확인 메시지를 출력하고 확인 버튼을 함께 생성-->
            <input type="submit" value="Delete" class="btn btn-danger">
        </form>
    {% endblock %}

</body>
</html>

bookmark/templates/bookmark/bookmark_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% extends 'base.html' %}

    {% block title %}
        Bookmark Add
    {% endblock %}

    {% block content %}
        <!--form 태그는 html로부터 서버 자료를 전달하기 위해 사용하는 코드
            action 메서드는 자료를 전달할 대상 페이지를 의미하고, 비워 둘 경우 현재 페이지로 전달
            method는 HTTP 메서드 종류를 설정-->
        <form action="" method="post">
            {% csrf_token %}<!--csrf_token :  공격을 막기 위한 용도 -> 해커가 외부 사이트에서 우리가 만든 사이트에 로그인 한 사용자 권한으로 공격하는 것을 막기 위한 용도-->
            {{form.as_p}}<!--form.as_p : 가각의 폼 필드와 라벨을 함께 문단, 즉 <p> 태그로 감싸서 출력-->
            <input type="submit" value="Add" class="btn btn-info btn-sm">
        </form>
    {% endblock %}

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% extends 'base.html' %}

    {% block title %}
        Bookmark Add
    {% endblock %}

    {% block content %}

    <!--제너릭 뷰잉ㄴ DetailView가 object라는 이름으로 북마크의 값을 전달,
        object 변수를 이용하여 하나씩 출력,
        확인 뷰는 큰 용도는 없기 때문에, 특별한 구조없이 값만 출력함-->
        {{object.site_name}}<br/>
        {{object.url}}

    {% endblock %}

</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
    {% extends 'base.html' %}

    {% block title %}
        Bookmark Add
    {% endblock %}

    {% block content %}
        <div class="btn-group"> <!--북마크 추가하기 링트 생성-->
            <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
        </div>
        <p></p>
        <table class="table"> <!--북마크 목록을 출력하기 위해 table 태그 이용-->
            <thead>
            <tr>
                <th scope="co1">#</th>
                <th scope="co1">Site</th>
                <th scope="co1">URL</th>
                <th scope="co1">Modify</th>
                <th scope="co1">Delete</th>
            </tr>
            </thead>
            <tbody>
                <!--제어릭 뷰(클래스 뷰) 에서는 모델의 오브젝트가 여러 개일 경우, object_list라는 변수로 전달-->
                {% for bookmark in object_list %} <!--object_list에서 bookmark 라는 이름으로 북마크를 하나씩 꺼내 북마크 당 한 줄 씩 출력한 것-->
                    <tr> <!--한 북마크는 tr 태그로 묶음-->
                        <!--각각의 북마크를 출력할 때 사이트 이름 url 등을 출력하고 수정 버튼과 지우기 버튼 생성-->
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{bookmark.site_name}}</a> </td>
                        <td> <a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a> </td>
                        <td> <a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a> </td>
                        <td> <a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a> </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock %}

    {% block pagination %}
        {% if is_paginated %}
        <ul class="pagination justify-content-center pagination-sm">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for object in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
                    <a class="page-link" href="{{request.path}}?page={{forloop.counter}}">{{forloop.counter}}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'list' %}?page={{page_obj.next_page_number}}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
        {% endif %}
    {% endblock %}

bookmark/templates/bookmark/bookmark_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% extends 'base.html' %}

    {% block title %}
        Bookmark Add
    {% endblock %}

    {% block content %}
    <!--bookmark_create.html과 동일하게 만들고 버튼 값만 Update로 변경-->
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-info btn-sm">
      </form>
    {% endblock %}

</body>
</html>