blog/urls.py
from django.urls import path
from .import views

app_name = 'blog' # 블로그 앱의 url에 name space 설정하도록 변경

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
'''
polls/views.py에서 생성한 뷰를 호출하기 위한 URL파일 생성
'''

from django.urls import path
from .import views

# path 함수는 path(route, view, kwargs, name) 형태로 호출
# route : 주소
# view : route의 주소로 접근했을 때 호출할 view
# kwargs : 뷰에 전달할 값들
# name : route의 이름, 원하는 곳에서 주소를 호출해 출력하거나 사용 가능

app_name = 'polls' # URL 네임스페이스 설정

''' ## Function-based view
urlpatterns=[
    path('', views.index, name='index'), # ex: /polls/
    
    #path converter : <>는 변수 의미, 해당 값을 뷰에 인자로 전달
    path('<int:question_id>/', views.detail, name='detail'), # ex: /polls/5/
    path('<int:question_id>/results/', views.results, name='results'), # ex: /polls/5/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), # ex:/polls/5/vote/
]'''

### Generic view(class-based view)
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'), # as_view() : 진입 메소드
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), # ex: /polls/5/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'), # ex: /polls/5/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), # ex:/polls/5/vote/
]

polls/models.py
'''
설문조사 앱 구현하기
'''
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

'''Question, Choice 테이블 정의'''
'''Question 클래스 : __str__() 및 was_published_recently() 함수 추가, 
Choice 클래스 : __str__() 함수 추가'''

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    '''was_published_rencently 출력 모양 변경
            admin_order_field : 정렬 기준 항목, 
            boolean : 값이 Boolean 형태인지 설정하고, True이면 값 대신 아이콘으로 표시
            short_description : 항목의 헤더 이름 설정'''
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect # 라다이렉트 기능 사용
from .models import Question, Choice
from django.template import loader
from django.urls import reverse # URL 처리를 위해 request 객체는 필수 인자, question_id 인자를 받음
                                # path('<int:question_id>/vote/', views.vote, name='vote')

# Create your views here.

'''웹 클라이언트가 polls 앱에 접속하면, 간단한 문장을 응답하는 예제'''
"""
# 뷰 생성, 메시지 출력
def index(request):
    #return HttpResponse("Hello, world. You're at the polls index.")

    # latest_question_list 객체를 Question 테이블 객체에서 pub_date 컬럼의 역순으로 정렬하여 5개의 최근 Question 객체를 가져와서 만든다.
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    ##output = ', '.join([q.question_text for q in latest_question_list]) # ', '.join는 구분자를 포함한 문자열을 반환
    ##return HttpResponse(output)

    '''뷰에서 loader를 이용하여 템플릿 불러오도록 수정
    loader 함수를 이용하여 html 불러오고, 미리 만들어둔 투표 목료 context 라는 변수를 이용해 정달 -> render() 단축 함수로 대체 가능'''
    ###template = loader.get_template('polls/index.html')
    context = {'latest_question_list': latest_question_list,}
    ###return HttpResponse(template.render(context, request))
    # render() 함수를 이용하여 템플릿 불러오기
    return render(request, 'polls/index.html', context)

''' 여러 가지 뷰 추가(index:투표목록, detail:투표상세, vote:투표기능, results:투표결과) '''
# 404 error : 해당 데이터가 존재하지 않을 때 발생시키는 오류
# 상세 정보를 불러올 수 있는 투표 항목이 없을 경우 404 오류 발생 -> 단축함수 get_object_or_404로 대체 가능
def detail(request, question_id):
    #return HttpResponse("You're looking at question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

# 뷰함수 정의, question_id는 url.py에서 path('<int:question_id>/results/', views.results, name='results') 라인 실행 후 들어옴
def results(request, question_id):
    #response = HttpResponse("Your're looking at the results of question %s." % question_id)
    #return response
    question = get_object_or_404(Question, pk=question_id)
    '''render() 함수 사용, 템플릿으로 question 변수를 넘겨주는 것은 동일하지만 템플릿 파일이 다르므로, 사용자에게 보여주는 화면이 달라짐, 
       results() 뷰 함수는 최종적으로 results.html 템플릿 코드를 렌더링한 결과인 HTML 텍스트 데이터를 담은 HttpResponse 객체를 반환'''
    return  render(request, 'polls/results.html', {'question': question})

# 결과를 출력하는 result 뷰 변경, 각 답변 항목과 추표 수를 한꺼번에 보여줌
def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        '''Chocie 테이블을 검색, 검색조건은 pk=request_id, 
           request.POST는 제출된 폼의 데이터를 담고 있는 개체로서, 파이썬 사전처럼 request.POST['choice']는 폼 데이터에서 키가 'choice'에 해당하는 값인 choice.id를 스트림으로 리턴'''
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    # 폼의 POST 데이터에서 'choice'라는 키가 없으면 keyError 인셉션 발생, 검색 조건에 맞는 객체가 없으면 Choice.DoesNotExist 익셉션 발생
    except(KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form

        # 익셉션이 발생하면, render() 함수에 의해서 question과 error_message 컨텍스트 변수를 detail.html 템플릿으로 전달,
        # 그 결과 사용자에게는 에러 메시지와 함께 질문 항목 폼을 다시 보여줘서 데이터를 재입력하도록 함
        # detail.html에서 error_message 처리하는 부분과 연결됨
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else: # 다음 익셉션이 처리되지 않고 정상 처리하는 경우
        selected_choice.votes += 1 # Choice 객체의 votes 속성, 즉 선택 카운트를 +1 증가시킴
        selected_choice.save() # 변경 사항을 Choice 테이블에 저장

        # vote() 뷰 함수에서 HttpResponseRedirect 객체 반환, 리다이렉트할 타겟 URL을 인자로 받음, 타겟 URL은 reverse() 함수로 만든다.
        # HttpResponseRedirect(url) 별다른 Response를 반환하는게 아니라, 지정된 url 페이지로 refirect 할시 적용됨
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
"""

from django.views import generic

'''제너릭 뷰로 변환'''
### Generic View (class-based views)

'''generic.ListView : 특정 모델의 리스트를 출력해주는 뷰
    어떤 모델(model)에 대해 어떻게 리스트를 얻어올지 쿼리가 필요하고(queryset), 이것을 어느 템플릿(templates_name)에 어떤 파라미터명으로 전달할지(context_object_name)을 정의해야 함'''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list' # context_object_name : html에 전달할 파라미터명 지정

    '''Return the last five published questions.'''
    def get_queryset(self): # get_queryset() : 데이터베이스에 query할 객체를 정하는 함수, 템플릿으로넘겨줄 model 리턴
        return Question.objects.order_by('-pub_date')[:5]

'''generic.DetailView :  특정 모델의 특정 오브젝트에 대한 자세한 정보를 출력해주는 뷰
        어떤 모델(model)의 어떤 오브젝트(pk)를 어느 템플릿(template_name)에 어떤 파라미터명(context_object_name)으로 전달할지를 정의해주어야 함'''
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else: # 다음 익셉션이 처리되지 않고 정상 처리하는 경우
        selected_choice.votes += 1 # Choice 객체의 votes 속성, 즉 선택 카운트를 +1 증가시킴
        selected_choice.save() # 변경 사항을 Choice 테이블에 저장
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--
폼 만들기
투표 기능 동작 구현
detail.html 및 vote 뷰 수정
-->

    <h1>{{question.question_text}}</h1> <!--질문을 제목으로 사용하기 위해 폰트 크기를 <h1>로 지정-->
    <!--에러가 있으면 에러를 굵은 글자로 화면에 보여줌, view() 함수에서 보내주는 에러 메시지-->
    {% if error_message %}
        <p> <strong>{{error_message}}</strong> </p>
    {% endif %}

    <!--폼에 입력된 데이터는 POST 방식으로 보내줌, <form action> 속성에 {퍼센트 url 퍼센트} 템플릿 태그를 사용하여 받을 곳의 URL을 polls:vote로 지정함,
        URLConf에서 지정한 URL 패턴 이름, question.id가 question_id로 전달됨-->
    <form action="{% url 'polls:vote' question.id %}" method="post">
        <!--csrf_token은 CSRF 공격을 막기 위한 수단, 방금 서버로 들어온 요청이 사이트 내부에서 온 것이 맞는지 확인하는 용도로 사용-->
        {% csrf_token %}
        <!--detail() 뷰 함수에서 템플릿으로 넘겨준 Question 객체 순회, question.choice_set.all은 Question 객체의 chocie_set 속성에 들어있는 항목 모두를 의미-->
        {% for choice in question.choice_set.all %}
            <!--라디오 버튼으로 답변 항목 보여줌, 해당 라디오 버튼을 선택하면, POST 데이터가 'chocie'='3'(choice.id) 형태로 구성되도록 name과 value 속성을 정의,
                forloop.counter : 반복문의 반복 횟수를 출력하는 템플릿 문법-->
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <!--<label for> 속성과 <input id> 속성 값이 같아야 서로 바인딩 됨-->
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label> <br>
        {% endfor %}
        <input type="submit" value="Vote"> <!--vote 버튼을 클릭하면 사용자가 선택한 폼 데이터가 POST 방식으로 polls:vote URL로 전송됨.
                                                vote() 뷰 함수에서 request.POST['choice'] 구문으로 액세서함,
                                                <input> 태그의 name과 value 속성값들이, request.POST 사전에 key, value로 사용됨-->

    </form>

<!--
Question 객체의 choice_set 속성
Question과 Choice 테이블의 관계를 1:N 관계이고, 외래키로 연결됨
1:N 관계에서 1 테이블에 연결된 N 테이블의 항목들이라는 의미로, xxx_set 속성을 dedault로 제공함
-->
<!--
    <ul>
        # question.choice_set.all() : Question 테이블의 question 레코드에 연결된 Choice 테이블의 레코드를 모두 의마함
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
        {% endfor %}
    </ul>
    {{question}}
-->

</body>
</html>

polls/templates/polls/index.html
<!--MTV 패턴으로 수정 - index 뷰와 템플릿-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- style.css 파일을 불러와 사용할 수 있도록 내용 추가-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>

    {% if latest_question_list %}  <!--latest_question_list 객체는 index() 뷰 함수에서 넘겨주는 파라미터-->
        <!--<ul>~</ul> : latest_question_list 객체의 내용을 순회하면서 question_text를 순서 없는 리스트로 화면에 보여줌
        또한, 각 텍스트에 URL링크를 연결함, URL 링크는 /polls/3과 같은 형식임-->
        <ul>
            {% for question in latest_question_list %}
                <!--url을 변경하고 싶으면 polls/urls.py의 내용을 변경,
                    polls.urls 모듈에 작성된 URL path()에 정의된 name을 탐색하고, 뒤에는 넘겨줘야 하는 인자 question.id를 작성-->
                <li> <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a> </li>
            {% endfor %}
        </ul>
    <!--만일 latest_question_list 객체에 내용이 없다면, "No polls are available." 문장을 화면에 보여줌-->
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

  <h1>{{question.question_text}}</h1> <!--질문을 제목으로 사용하기 위해 폰트 크기를 <h1>로 설정-->
  <ul>
    {% for choice in question.choice_set.all %} <!--Choice 객체 순회-->
      <!--Choice 객체의 choice_text를 순서 없는 리스트로 화면에 보여줌, 각 텍스트 옆에 투표 카운트(choice.votes)를 숫자로 보여줌,
          vote{{choice.votes|pluralize}}는 choice.votes값에 따라 복수 접미사(s)를 붙여주는 것, 결과적으로 choice.votes 값에 따라 votes가 표시됨-->
      <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
  </ul>
  <a href="{% url 'polls:detail' question.id %}">Vote again?</a> <!--Vote Again? 이라는 문장을 보여주고, 그 문장에 URL 링크 연결결->

</body>
</html>