blog/urls.py
from django.urls import path
from .import views

app_name = 'blog' # 블로그 앱의 url에 name space 설정하도록 변경

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm): # ModelForm : Django에서 제공하는 model form

    class Meta:# -> class Meta : 이 폼을 만들기 위해서 어떤 model이 쓰여야하는지 장고에서 알려주는 구문
        model = Post
        fields = ('title', 'text',) # 폼에 보여질 양식(title, text)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm

# Create your views here.
def post_list(request):
    # published_date_lte=timezone.now() : 포스팅 목록 중에 published_date가 현재시간보다 작거나 같은 Post만 필터링하겠다는 뜻
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts}) # render() : 장고의 뷰에서 일련의 처리가 끝난 후 return 값으로 render

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()

    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet"> <!--구글 글꼴에서 Lobster라는 글꼴-->
    <title>Title</title>

</head>
<body>

    <div class="page-header">
        {% if user.is_authenticated %} <!--로그인한 사람만 글을 등록하게 만들기-->
            <a href="{% url 'blog:post_new' %}" class="top-menu"> <span class="glyphicon glyphicon-plus"></span> </a><!--글 추가 아이콘 생성(+)-->
        {% endif %}
        <h1> <a href="{% url 'blog:post_list' %}">HYWU Blog</a> </h1> <!--제목 링크 연결(어느화면에서도 제목을 누르면 리스트로 돌아감)-->
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>


</body>
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% extends 'blog/base.html' %}

  {% block content %}
    <div class="post">
      {% if post.published_date %}
        <div class="date">
          {{ post.published_date }}
        </div>
      {% endif %}

      {% if user.is_authenticated %} <!--로그인한 사람만 글을 등록하게 만들기-->
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"> <span class="glyphicon glyphicon-pencil"></span> </a> <!--글 수정 아이콘 생성-->
      {% endif %}
      <h1>{{ post.title }}</h1>
      <p>{{ post.text|linebreaksbr }}</p>
      </div>
  {% endblock %}
</body>
</html>

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for  post in posts %}
        <div class="post">
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <h1> <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1><!--상세페이지로 연결하는 링크 생성-->
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}